server:
  port: 8001

spring:
  application:
    name: cloud-payment-service
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.132.67.200:3306/db2019?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=GMT%2B8&tinyInt1isBit=true&useAffectedRows=true&nullCatalogMeansCurrent=true&allowPublicKeyRetrieval=true&allowMultiQueries=true&rewriteBatchedStatements=true
    username: root
    password: root123

springfox:
  documentation:
    swagger:
      v2.path: /api-docs
swagger:
  base-package: com.ie.springcloud.controller


mybatis-plus:
  type-aliases-package: com.ie.entity
  mapper-locations: "classpath*:/mappers/**/*.xml"
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-field: flag  # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
eureka:
  instance:
    instance-id: payment8001
    prefer-ip-address: true #访问路径可以显示ip地址
    #客户端向服务端发送心跳的时间间隔，单位为秒（默认30秒）
#    lease-renewal-interval-in-seconds: 1
    #eureka服务端在收到最后一次心跳后等待时间上限，单位是秒（默认90秒），超时将剔除服务
#    lease-expiration-duration-in-seconds: 2
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      #集群版
#      defaultZone: http://eureka7002.com:7002/eureka/,http://eureka7001.com:7001/eureka/
      #单机版
      defaultZone: http://eureka7001.com:7001/eureka/